using DefaultDocumentation.Api;
using DefaultDocumentation.Markdown.Extensions;

namespace DefaultDocumentation.Markdown.Sections
{
    /// <summary>
    /// <see cref="ISection"/> implementation to write a link to <see href="https://github.com/Doraku/DefaultDocumentation">DefaultDocumentation</see>.
    /// </summary>
    public sealed class FooterSection : ISection
    {
        /// <summary>
        /// The name of this implementation used at the configuration level.
        /// </summary>
        public const string ConfigName = "Footer";

        /// <inheritdoc/>
        public string Name => ConfigName;

        /// <inheritdoc/>
        public void Write(IWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);

            if (writer.GetCurrentItem() != writer.Context.DocItem)
            {
                return;
            }

            writer
                .EnsureLineStartAndAppendLine()
                .AppendLine("---")
                .Append("Generated by ")
                .AppendUrl("https://github.com/Doraku/DefaultDocumentation", "DefaultDocumentation");
        }
    }
}
