using DefaultDocumentation.Markdown.Extensions;
using DefaultDocumentation.Api;

namespace DefaultDocumentation.Markdown.Sections
{
    public sealed class FooterSection : ISection
    {
        public string Name => "Footer";

        public void Write(IWriter writer)
        {
            if (writer.GetCurrentItem() != writer.DocItem)
            {
                return;
            }

            writer
                .EnsureLineStartAndAppendLine()
                .AppendLine("---")
                .Append("Generated by ")
                .AppendUrl("https://github.com/Doraku/DefaultDocumentation", "DefaultDocumentation");
        }
    }
}
