using DefaultDocumentation.Markdown.Extensions;
using DefaultDocumentation.Models;
using Xunit;

namespace DefaultDocumentation.Markdown.Sections.FooterSectionTests;

public sealed class WriteShould : BaseSectionTester<FooterSection>
{
    private static readonly AssemblyDocItem _assemblyItem = new("dummy", "dummy", null);

    [Fact]
    public void NotWriteWhenNotPageItem() => Test(
        w => w.SetCurrentItem(_assemblyItem),
        string.Empty);

    [Fact]
    public void Write() => Test(
@"---
Generated by [DefaultDocumentation](https://github.com/Doraku/DefaultDocumentation 'https://github.com/Doraku/DefaultDocumentation')");

    [Fact]
    public void WriteNewlineWhenNeeded() => Test(
        w => w.Append("pouet"),
@"pouet

---
Generated by [DefaultDocumentation](https://github.com/Doraku/DefaultDocumentation 'https://github.com/Doraku/DefaultDocumentation')");
}
