name: code coverage

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/CodeCoverage.yml'
      - 'source/DefaultDocumentation.Api/**'
      - 'source/DefaultDocumentation.Markdown/**'
      - 'source/DefaultDocumentation.Test/**'

jobs:
  code_coverage:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Collect coverage
      run: dotnet test source -c Release
      env:
        CollectCoverage: true
        CoverletOutputFormat: lcov
        CoverletOutput: ..\..\build\lcov.info
        TEST: true

    - name: Upload to coverall
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'build\lcov.info'
