name: code coverage

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/CodeCoverage.yml'
      - 'source/**'

jobs:
  code_coverage:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Collect coverage
      run: dotnet test source\DefaultDocumentation.sln -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=..\..\build\lcov.info -p:Exclude="[*]System.Diagnostics.CodeAnalysis.*" /p:TEST=true

    - name: Upload to coverall
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: 'build\lcov.info'
