name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/DefaultDocumentation/**'
      - 'source/DefaultDocumentation.Api/**'
      - 'source/DefaultDocumentation.Common/**'
      - 'source/DefaultDocumentation.Console/**'
      - 'source/DefaultDocumentation.Markdown/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build
      run: dotnet build source\DefaultDocumentation.sln -c Release -p:TreatWarningsAsErrors=true /p:TEST=true

    - name: Run tests
      run: dotnet test source\DefaultDocumentation.sln -c Release --no-build
      
    - name: Decrypte snk file
      env:
        SNK_KEY: ${{ secrets.SNK_KEY }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$env:SNK_KEY" --output ds.snk ds.snk.gpg

    - name: Create package
      run: |
        dotnet pack source\DefaultDocumentation.sln -c Release -o build /p:CI_VERSION=true

    - name: Publish packages
      run: nuget push build\*.nupkg
