name: pull request

on:
  pull_request:
    paths:
      - 'source/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'
        
    - name: Build
      run: dotnet build source -c Release -p:TreatWarningsAsErrors=true

    - name: Run tests
      run: dotnet test source -c Release --no-build
